env:
   - GHCVER=7.8.3
before_install:
    - sudo add-apt-repository -y ppa:hvr/ghc
    - sudo apt-get update
    - sudo apt-get install cabal-install-1.20 ghc-$GHCVER
    - export PATH=/opt/ghc/$GHCVER/bin:$PATH

install:
    - cabal update
    - cabal-1.20 sandbox init
    - cabal-1.20 sandbox add-source ./yesod-auth-kerberos
    - cabal-1.20 sandbox add-source ./shorten-strings
    - cabal-1.20 install --only-dependencies

script:
    - cabal-1.20 configure
    - cabal-1.20 build

notifications:
  irc: "irc.dtek.se#dhack"
