Default: &defaults
  user: dtekportalen
  password: DtekPortalen
  host: localhost
  port: 5432
  database: dtekportalen
  poolsize: 10

Development:
  <<: *defaults

Test:
  database: dtekportalen_test
  <<: *defaults

Staging:
  database: dtekportalen_staging

Production:
  database: dtekportalen 
  <<: *defaults
