Default: &defaults
  database: dtekportalen.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: dtekportalen_test.sqlite3
  <<: *defaults

Staging:
  database: dtekportalen_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: dtekportalen_production.sqlite3
  poolsize: 100
  <<: *defaults
